FROM python:3.9

WORKDIR /app

# Copy script from src/
COPY src/kafka_to_timescale.py ./

# Correct the path for requirements.txt
COPY requirements.txt ./

RUN pip install -r requirements.txt

CMD ["python", "kafka_to_timescale.py"]
