FROM python:3.9-slim

WORKDIR /app

# Copy and install dependencies
COPY requirements/fetcher.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy fetcher script
COPY src/fetch_stock_data.py ./

CMD ["python", "fetch_stock_data.py"]
