FROM python:3.9

WORKDIR /app

# Copy script from src/
COPY src/fetch_stock_data.py ./

# Correct the path for requirements.txt
COPY requirements.txt ./

RUN pip install -r requirements.txt

CMD ["python", "fetch_stock_data.py"]
